# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: rescue => MissingNutrient::VitaminE
author: tanukiti1987
summary: Tech関連では Ruby, Rails, Android, Arduino のことを書いていたり、気になったガジェットについて書いたり、読んだ本について書いたりしています。
keywords: tanukiti1987, ブログ, ruby, android, ios, iphone, zenfone

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://almond.milk200.cc"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - contact.html

google_analytics: UA-27693816-5

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname:

# Social icons
facebook_username: ryusuke.sekiguchi
github_username: tanukiti1987
instagram_username: tanukiti1987
linkedin_username: ryusuke-sekiguchi-778876117
twitter_username: tanukiti1987

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false

# Contact form ID
formspree: xgezgove

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'
  contact:
    email: example@example.com
    content: ご連絡いただく内容をご記入ください！
    submit: 送信する

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: /blog/:year/:month/:day/:title.html
paginate_path: "/page/:num/"
paginate: 5

# OGP default image
image: https://skim.milk200.cc/logo/almond.jpg

css_dir: "css"

plugins:
  - jekyll-auto-image
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-tfidf-related-posts
  - jekyll-purgecss

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - circle.yml
  - README.md
