# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: rescue => MissingNutrient::VitaminE
author:
  name: tanukiti1987
description: Tech関連では Ruby, Rails, Android, Arduino のことを書いていたり、気になったガジェットについて書いたり、読んだ本について書いたりしています。
keywords: tanukiti1987,ブログ,ruby,android,ios,iphone,zenfone

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://almond.milk200.cc"
permalink: /blog/:year/:month/:day/:title.html
twitter_username: tanukiti1987
github_username: tanukiti1987
paginate_path: "/page/:num/Index.html"
paginate: 5

# For tags
tag_page_layout: tag_page
tag_page_dir: blog/tag
tag_page_data:
  sitemap: false

feed:
  path: atom.xml

google_analytics_key: UA-27693816-5
facebook_username: ryusuke.sekiguchi
twitter_username: tanukiti1987
linkedin_username: ryusuke-sekiguchi-778876117
instagram_username: tanukiti1987
github_username:  tanukiti1987
feed_icon: rss

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - circle.yml
  - README.md
