defaults: &defaults
  docker:
    - image: tanukiti1987/blog-base:0.1
  working_directory: /home/ubuntu/blog
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            # if cache for exact version of `Gemfile` is not present then load any most recent one
            - bundle
      - run:
          name: bundle install
          command: |
              gem update bundler
              bundle -j8 --path=vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - run:
          name: jekyll build
          command: JEKYLL_ENV=production bundle exec jekyll build

  build-and-deploy:
    <<: *defaults
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            # if cache for exact version of `Gemfile` is not present then load any most recent one
            - bundle
      - run:
          name: bundle install
          command: |
              gem update bundler
              bundle -j8 --path=vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - run:
          name: jekyll build
          command: JEKYLL_ENV=production bundle exec jekyll build
      - run:
          name: sync to s3
          command: bundle exec s3_website push
      - run:
          name: invalidate cloudfront
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
