version: 2.1
executors:
  blog-base:
    docker:
      - image: tanukiti1987/blog-base:0.4
    working_directory: /root/blog
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"

commands:
  bundle-install:
    description: "bundle install"
    steps:
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            # if cache for exact version of `Gemfile` is not present then load any most recent one
            - bundle
      - run:
          name: bundle install
          command: |
              gem update bundler
              bundle -j8 --path=vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: /root/blog/vendor/bundle

jobs:
  build:
    executor: blog-base
    steps:
      - checkout
      - bundle-install
      - run:
          name: jekyll build
          command: JEKYLL_ENV=production bundle exec jekyll build
      - persist_to_workspace:
          root: /root
          paths: blog
  deploy:
    executor: blog-base
    steps:
      - attach_workspace:
          at: /root
      - bundle-install
      - run:
          name: sync to s3
          command: bundle exec s3_website push
      - run:
          name: invalidate cloudfront
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
