defaults: &defaults
  docker:
    - image: tanukiti1987/blog-base:0.1
  working_directory: /root/blog
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            # if cache for exact version of `Gemfile` is not present then load any most recent one
            - bundle
      - run:
          name: bundle install
          command: |
              gem update bundler
              bundle -j8 --path=vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: /root/blog/vendor/bundle
      - run:
          name: jekyll build
          command: JEKYLL_ENV=production bundle exec jekyll build
      - persist_to_workspace:
          root: /root
          paths: blog
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: bundle install
          command: |
              gem update bundler
              bundle -j8 --path=vendor/bundle
      - run:
          name: sync to s3
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
